permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

# source: source
# destination: _site
# sass:
#   sass_dir: _sass
#   style: compressed

# Site settings
title: Yucen Luo
description: "Home"
email: luoyc15@mails.tsinghua.edu.cn
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com"
url: "http://xinmei9322.github.io"
repository: "https://github.com/xinmei9322/xinmei9322.github.io"
disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1

# social footer
social:
  github:
    slug: github
    link: https://github.com/xinmei9322
  facebook:
    slug: facebook
    link: http://facebook.com/fernando.dev
  twitter:
    slug: twitter
    link: http://twitter.com/nandomoreirame
  instagram:
    slug: instagram
    link: http://instagram.com/nandomoreira.me
  linkedin:
    slug: linkedin
    link: http://linkedin.com/in/nandomoreirame
